# Use DecapBridge classic auth (required)
backend:
  name: git-gateway
  repo: dCastanho/corvos
  branch: master
  identity_url: https://auth.decapbridge.com/sites/400eaace-5a20-4e46-bfe7-a6492ee1f281
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
media_folder: /public/

collections:
- name: 'evento'
  label: 'Evento'
  folder: '/event/'
  create: true
  slug: '{{slug}}'
  editor:
    preview: true
  fields:
  - {label: "Titulo", name: "title", widget: "string"}
  - {label: "Corpo", name: "body", widget: "markdown"}
- name: 'about'
  label: 'Sobre'
  folder: '/about/'
  create: true
  slug: '{{slug}}'
  editor:
    preview: true
  fields:
  - {label: "Titulo", name: "title", widget: "string"}
  - {label: "Corpo", name: "body", widget: "markdown"}
- name: 'battles'
  label: 'Batalhas'
  folder: '/about/batalhas/'
  create: true
  slug: '{{title}}'
  fields:
  - {label: "Ano", name: "title", widget: "number"}
  - {label: "Participantes", name: "participants", widget: "number"}
  - {label: "Local", name: "local", widget: "string"}
- name: 'battles_index'
  label: 'Lista de Batalhas'
  folder: '/about/batalhas/'
  slug: '{{slug}}'
  filter:
    field: title
    value: Lista
  fields:
  - {label: "Titulo", name: "title", widget: "string"}
  - {label: "Corpo", name: "body", widget: "markdown"}
- name: 'inicio'
  label: 'Inicio'
  folder: '/'
  create: true
  slug: '{{slug}}'
  fields:
  - {label: "Titulo", name: "title", widget: "string"}
  - {label: "Corpo", name: "body", widget: "markdown"}

logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://dcastanho.github.io